# Ten ung dung
spring.application.name=Smart_Attendance_Enterprise_LMS

# Ket noi CSDL PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# Cau hinh JPA / Hibernate
# Hibernate 6+ (Spring Boot 3.x) tu dong nhan dien PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tu dong tao/cap nhat bang trong CSDL tu Entity (Dung update khi dev)
spring.jpa.hibernate.ddl-auto=update

# Hien thi cau lenh SQL va Format ra console de debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

